import { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function No_NBGroupLayout(props: PropsWithChildren) {
  return <>{props.children}</>;
}
